CREATE TABLE [stage].[ZipCode_RealEstate_History_USA] (
    [month_date_yyyymm]                       VARCHAR (100) NOT NULL,
    [median_listing_price]                    VARCHAR (100) NULL,
    [median_listing_price_mm]                 VARCHAR (100) NULL,
    [median_listing_price_yy]                 VARCHAR (100) NULL,
    [active_listing_count]                    VARCHAR (100) NULL,
    [active_listing_count_mm]                 VARCHAR (100) NULL,
    [active_listing_count_yy]                 VARCHAR (100) NULL,
    [median_days_on_market]                   VARCHAR (100) NULL,
    [median_days_on_market_mm]                VARCHAR (100) NULL,
    [median_days_on_market_yy]                VARCHAR (100) NULL,
    [new_listing_count]                       VARCHAR (100) NULL,
    [new_listing_count_mm]                    VARCHAR (100) NULL,
    [new_listing_count_yy]                    VARCHAR (100) NULL,
    [price_increased_count]                   VARCHAR (100) NULL,
    [price_increased_count_mm]                VARCHAR (100) NULL,
    [price_increased_count_yy]                VARCHAR (100) NULL,
    [price_reduced_count]                     VARCHAR (100) NULL,
    [price_reduced_count_mm]                  VARCHAR (100) NULL,
    [price_reduced_count_yy]                  VARCHAR (100) NULL,
    [pending_listing_count]                   VARCHAR (100) NULL,
    [pending_listing_count_mm]                VARCHAR (100) NULL,
    [pending_listing_count_yy]                VARCHAR (100) NULL,
    [median_listing_price_per_square_foot]    VARCHAR (100) NULL,
    [median_listing_price_per_square_foot_mm] VARCHAR (100) NULL,
    [median_listing_price_per_square_foot_yy] VARCHAR (100) NULL,
    [median_square_feet]                      VARCHAR (100) NULL,
    [median_square_feet_mm]                   VARCHAR (100) NULL,
    [median_square_feet_yy]                   VARCHAR (100) NULL,
    [average_listing_price]                   VARCHAR (100) NULL,
    [average_listing_price_mm]                VARCHAR (100) NULL,
    [average_listing_price_yy]                VARCHAR (100) NULL,
    [total_listing_count]                     VARCHAR (100) NULL,
    [total_listing_count_mm]                  VARCHAR (100) NULL,
    [total_listing_count_yy]                  VARCHAR (100) NULL,
    [pending_ratio]                           VARCHAR (100) NULL,
    [pending_ratio_mm]                        VARCHAR (100) NULL,
    [pending_ratio_yy]                        VARCHAR (100) NULL,
    [quality_flag]                            VARCHAR (100) NULL,
    [postal_code]                             VARCHAR (100) NOT NULL,
    [zip_name]                                VARCHAR (100) NULL,
    CONSTRAINT [PK_dbo_ZipCode_RealEstate_History_USA] PRIMARY KEY CLUSTERED ([month_date_yyyymm] ASC, [postal_code] ASC)
);

